#!/usr/bin/env bash
# fizzbuzz challenge

i=1
while [ $i -lt 101 ];
do
    if [[ $(expr $i % 3) == "0" ]] && [[ $(expr $i % 5) == "0" ]]
    then
	echo "FizzBuzz"
    elif [[ $(expr $i % 3) == "0" ]]
    then
	 echo "Fizz"
    elif [[ $(expr $i % 5) == "0" ]]
    then
	echo "Buzz"
    else
	echo $i
    fi
    ((i++))
done
	
