#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

cp -n /etc/hosts new_hosts
#sed -i s/^127.*/"127.0.0.2 localhost"/ new_hosts
#"8.8.8.8 facebook.com" > new_hosts
echo "$(cat new_hosts)" > /etc/hosts

